# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('routine_type', models.IntegerField()),
                ('equipment_needed', models.IntegerField()),
                ('days_per_week', models.IntegerField()),
                ('session_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Exercise')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Workout'),
        ),
    ]
