# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20170323_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='equipment_needed',
            field=models.CharField(choices=[('Minimal', 'Basic Gym Equipment'), ('Extensive', 'Extensive Gym Equipment')], max_length=30),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='recommender.Exercise'),
        ),
    ]
