# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20170323_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='workout',
        ),
        migrations.AddField(
            model_name='routine',
            name='workout',
            field=models.ManyToManyField(to='recommender.Workout'),
        ),
    ]
