# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20170323_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='equipment_needed',
            field=models.CharField(choices=[('0', 'Basic Gym Equipment'), ('1', 'Extensive Gym Equipment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='routine',
            name='routine_type',
            field=models.IntegerField(choices=[('Strength', 'Strength'), ('Hypertrophy', 'Hypertrophy')]),
        ),
    ]
