# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='Exercise',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='User',
            new_name='user',
        ),
    ]
